<?php
	function navigation(){
		echo '<div class="menu_block ">
						<div class="container_12">
							<div class="grid_12">
								<nav class="horizontal-nav full-width horizontalNav-notprocessed">
									<ul class="sf-menu">
										<li class="current"><a href="index.php">Home</a></li>
										<li><a href="about.php">About</a></li>
										<li><a href="#">Cars</a></li>
										<li><a href="#">Services</a></li>
										<li><a href="#">Contacts</a></li>
									</ul>
								</nav>
								<div class="clear"></div>
							</div>
							<div class="clear"></div>
						</div>
					</div>';
	}
	
	function logo(){
		echo '<div class="container_12">
						<div class="grid_12">
							<h1>
								<a href="index.php">
									<img src="images/logo.png" alt="Your Happy Family">
								</a>
							</h1>
						</div>
					</div>
					<div class="clear"></div>';
	}
	
	function footer(){
		echo '<div class="container_12">
						<div class="grid_12">
							<div class="f_phone"><span>Call Us:</span> + 6285 2240 57100</div>										
								<div class="st1">		
									<div class="pull-left">
										<div class="brand">Support Team</div>														
										<br><br>
										<ul class="list1">
											<li><a href="http://www.unikom.ac.id" target="_blank">UNIKOM</a></li>
											<li><a href="#">UNIKOM</a></li>
											<li><a href="#">UNIKOM</a></li>
											<li><a href="#">UNIKOM</a></li>
											<li><a href="#">UNIKOM</a></li>
										</ul>
									</div>
								</div>
								<br>
								<div class="st1">
									<div class="copy pull-right">
										<div class="brand">
											Imancha<span class="color1">T</span>our 
										</div>
										&copy; 2014
								</div>
							</div>
						</div>					
					</div>				
					<div class="clear"></div>';
	}
?>
